@startuml TeacherCreateLesson_Flow

!theme plain
title Giao vien Tao Bai Hoc

skinparam ActivityBackgroundColor #E1BEE7
skinparam ActivityBorderColor #7B1FA2
skinparam DecisionBackgroundColor #FFF9C4

start

:Dang nhap;

:Nhap "Tao Bai hoc moi";

:Dien:
- Tieu de, Tom tat
- Danh muc;

:Soan noi dung;

if (Hop le?) then (Khong)
    :Sua lai;
else (Co)
endif

:Chon trang thai:
Published / Draft;

:Tao;

:Luu vao DB;

:Hoan thanh;

stop

@enduml
