export const LESSON_SECTIONS = [
  {
    id: 'landmarks',
    title: 'Lịch sử các địa danh',
    shortTitle: 'Địa danh',
    description: 'Khám phá lịch sử các huyện, thị trấn và địa danh tiêu biểu của tỉnh Lâm Đồng.',
    heroTitle: 'Hành trình qua những địa danh nổi bật của Lâm Đồng',
    heroDescription:
      'Từ Đà Lạt thơ mộng đến những vùng đất anh hùng, từng địa danh đều mang trong mình một câu chuyện hình thành và phát triển đáng tự hào.',
    searchPlaceholder: 'Tìm kiếm địa danh, huyện thị hoặc nội dung liên quan...',
    accent: 'from-sky-500 via-cyan-500 to-blue-500',
    badgeColor: 'text-sky-600 bg-sky-100',
    icon: 'MapPin',
    comingSoon: false,
  },
  {
    id: 'figures',
    title: 'Lịch sử các nhân vật',
    shortTitle: 'Nhân vật',
    description: 'Những nhân vật kiệt xuất gắn liền với quá trình hình thành và phát triển của vùng đất cao nguyên.',
    heroTitle: 'Những con người làm nên lịch sử Lâm Đồng',
    heroDescription:
      'Khám phá cuộc đời, sự nghiệp và di sản mà các nhân vật nổi bật để lại cho vùng đất cao nguyên trù phú.',
    searchPlaceholder: 'Tìm kiếm nhân vật, câu chuyện hay sự kiện tiêu biểu...',
    accent: 'from-violet-500 via-purple-500 to-fuchsia-500',
    badgeColor: 'text-violet-600 bg-violet-100',
    icon: 'Sparkles',
    comingSoon: true,
  },
  {
    id: 'overview',
    title: 'Lịch sử tổng quan',
    shortTitle: 'Tổng quan',
    description: 'Bức tranh toàn cảnh về lịch sử, văn hóa và những dấu ấn quan trọng của Lâm Đồng.',
    heroTitle: 'Nhìn lại chặng đường phát triển của Lâm Đồng',
    heroDescription:
      'Đặt Lâm Đồng trong dòng chảy lịch sử, từ những ngày đầu khai phá đến thời kỳ hội nhập và đổi mới.',
    searchPlaceholder: 'Tìm kiếm chủ đề tổng quan, giai đoạn lịch sử, dấu mốc...',
    accent: 'from-amber-500 via-orange-500 to-rose-500',
    badgeColor: 'text-amber-600 bg-amber-100',
    icon: 'Layers',
    comingSoon: true,
  },
];

export const SAMPLE_LESSONS = {
  figures: [
    {
      id: 'sample-figure-1',
      title: 'Khuất Phù: Người mở đường vùng đất cao nguyên',
      summary:
        'Câu chuyện về vị quan triều Nguyễn đã đặt nền móng cho sự hình thành vùng đất Đà Lạt với tầm nhìn chiến lược.',
      slug: '#',
      duration: '18 phút',
      difficulty: 'Trung bình',
      rating: 4.9,
      studyCount: 0,
      progress: 0,
      category: 'Nhân vật lịch sử',
      tags: ['Nhân vật', 'Đà Lạt', 'Triều Nguyễn'],
      images: [],
      instructor: 'Ban biên soạn Lịch sử Lâm Đồng',
      isSample: true,
    },
    {
      id: 'sample-figure-2',
      title: 'Bác sĩ Yersin và hành trình khám phá Lang Biang',
      summary:
        'Nhìn lại hành trình khám phá, những thách thức và di sản để lại của bác sĩ Alexandre Yersin tại cao nguyên Lâm Viên.',
      slug: '#',
      duration: '22 phút',
      difficulty: 'Cơ bản',
      rating: 5,
      studyCount: 0,
      progress: 0,
      category: 'Nhân vật lịch sử',
      tags: ['Khoa học', 'Khám phá', 'Lang Biang'],
      images: [],
      instructor: 'Ban biên soạn Lịch sử Lâm Đồng',
      isSample: true,
    },
    {
      id: 'sample-figure-3',
      title: 'Anh hùng K’Nai: Niềm tự hào bon làng',
      summary:
        'Gặp gỡ vị anh hùng người K’Ho đã lãnh đạo cộng đồng đứng lên bảo vệ bản sắc và vùng đất của mình.',
      slug: '#',
      duration: '15 phút',
      difficulty: 'Cơ bản',
      rating: 5,
      studyCount: 0,
      progress: 0,
      category: 'Nhân vật lịch sử',
      tags: ['Cộng đồng', 'Kháng chiến'],
      images: [],
      instructor: 'Ban biên soạn Lịch sử Lâm Đồng',
      isSample: true,
    },
  ],
  overview: [
    {
      id: 'sample-overview-1',
      title: 'Từ cao nguyên hoang sơ tới trung tâm du lịch',
      summary:
        'Bức tranh tổng quan về hành trình chuyển mình của Lâm Đồng trong hơn một thế kỷ qua.',
      slug: '#',
      duration: '20 phút',
      difficulty: 'Cơ bản',
      rating: 4.8,
      studyCount: 0,
      progress: 0,
      category: 'Lịch sử tổng quan',
      tags: ['Lịch sử', 'Kinh tế', 'Du lịch'],
      images: [],
      instructor: 'Ban biên soạn Lịch sử Lâm Đồng',
      isSample: true,
    },
    {
      id: 'sample-overview-2',
      title: 'Địa hình - khí hậu và tác động lịch sử',
      summary:
        'Tìm hiểu vì sao khí hậu ôn hòa, địa hình cao nguyên lại tác động mạnh mẽ tới lịch sử và con người Lâm Đồng.',
      slug: '#',
      duration: '17 phút',
      difficulty: 'Trung bình',
      rating: 4.7,
      studyCount: 0,
      progress: 0,
      category: 'Lịch sử tổng quan',
      tags: ['Địa lý', 'Văn hóa'],
      images: [],
      instructor: 'Ban biên soạn Lịch sử Lâm Đồng',
      isSample: true,
    },
  ],
};
